=== JMRBDev/1DAW/Lenguaje de Marcas/Tema 6 - XML-DTD/Relación de Ejercicios 2/Ejercicio 6/Apartado 1/liga1.dtd
<!ELEMENT liga (partido+)>
<!ELEMENT partido (equipoLocal,equipoVisitante,golesEquipoLocal,golesEquipoVisitante)>
<!ELEMENT equipoLocal (#PCDATA)>
<!ELEMENT equipoVisitante (#PCDATA)>
<!ELEMENT golesEquipoLocal (CDATA)>
<!ELEMENT golesEquipoVisitante (CDATA)>

=== JMRBDev/1DAW/Lenguaje de Marcas/Tema 6 - XML-DTD/Relación de Ejercicios 2/Ejercicio 6/Apartado 1/liga1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note SYSTEM "liga1.dtd">
<!-- Jose Rosendo Bienvenido -->
<liga>
    <partido>
        <equipoLocal>Nottingham Presa</equipoLocal>
        <equipoVisitante>Inter de Mitente</equipoVisitante>
        <golesEquipoLocal>0</golesEquipoLocal>
        <golesEquipoVisitante>1</golesEquipoVisitante>
    </partido>

    <partido>
        <equipoLocal>Vodka Juniors</equipoLocal>
        <equipoVisitante> Sparta da Risa</equipoVisitante>
        <golesEquipoLocal>3</golesEquipoLocal>
        <golesEquipoVisitante>3</golesEquipoVisitante>
    </partido>

    <partido>
        <equipoLocal>Water de Munich</equipoLocal>
        <equipoVisitante>Esteaua es del grifo</equipoVisitante>
        <golesEquipoLocal>4</golesEquipoLocal>
        <golesEquipoVisitante>2</golesEquipoVisitante>
    </partido>
</liga>
